name: widgets
description: Hybris common widgets.
version: 0.0.1
author: zhanhongbo1112
homepage: https://www.github.com/zhanhongbo1112

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  b2b_commerce:
    path: ../b2b_commerce/
  models:
    path: ../models/
  services:
    path: ../services/

  # json_annotation: ^2.0.0
  json_annotation: ^4.0.1
  dio: ^4.0.0
  # dio: 2.2.2
  shared_preferences: ^2.0.6
  transparent_image: ^2.0.0
  # flutter_staggered_grid_view: "^0.2.4"
  flutter_map: ^0.13.1
  image_picker: ^0.8.3+2
  scoped_model: ^1.1.0
  flutter_redux: ^0.8.2
  rxdart: ^0.26.0
  photo_view: ^0.12.0
  path_provider: ^2.0.2
  open_file: ^3.2.1
  month_picker_dialog: ^0.4.0
  # cached_network_image: ^0.7.0
  cached_network_image: 3.1.0
  flutter_spinkit: ^5.0.0
  cool_ui: "^1.0.2"
  crypto: ^3.0.1
  # image_gallery_saver: ^1.1.0
  image_cropper: ^1.2.1
  bot_toast: ^4.0.1
  video_player: ^2.1.12
  video_thumbnail: ^0.2.2
  flutter_image_compress: ^0.7.0
  wechat_assets_picker: 6.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - packages/assets/temp/pdf.png
    - packages/assets/temp/word.png
    - packages/assets/temp/excel.png
    - packages/assets/temp/login_background.png

  fonts:
    - family: b2bIcons
      fonts:
        - asset: lib/fonts/iconfont1.ttf
    - family: b2bIcons2
      fonts:
        - asset: lib/fonts/iconfont2.ttf
    - family: b2bIcons21
      fonts:
        - asset: lib/fonts/iconfont21.ttf
    - family: b2bIcons22
      fonts:
        - asset: lib/fonts/iconfont22.ttf
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
