name: widgets
description: Hybris common widgets.
version: 0.0.1
author: zhanhongbo1112
homepage: https://www.github.com/zhanhongbo1112

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  models:
    path: ../models/
  services:
    path: ../services/

  json_annotation: ^2.0.0
  cached_network_image: ^0.4.1+1
  cupertino_icons: ^0.1.2
  dio: 1.0.9
  shared_preferences: ^0.4.2
  transparent_image: ^0.1.0
  flutter_staggered_grid_view: "^0.2.4"
  flutter_map: ^0.1.4
  image_picker: ^0.4.10
  scoped_model: ^1.0.1
  flutter_redux: ^0.5.2
  rxdart: ^0.20.0
  fluwx: ^0.5.4
  photo_view: ^0.1.3
  open_file: ^1.1.1
  path_provider: ^0.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your package, add an assets section, like this:
  assets:
    - images/logo.png
  fonts:
    - family: b2bIcons
      fonts:
        - asset: lib/fonts/iconfont1.ttf
  #
  # For details regarding assets in packages, see
  # https://flutter.io/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.io/custom-fonts/#from-packages
