name: b2b_commerce
description: Hybris B2B Commerce.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.9.1+1

flutter_localizations:
  sdk: flutter

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  models:
    path: ../models/
  widgets:
    path: ../widgets/
  assets:
    path: ../assets/
  services:
    path: ../services/

  json_annotation: ^3.0.1
  font_awesome_flutter: 8.2.0
  dio: ^3.0.9
  shared_preferences: ^0.4.2
  transparent_image: ^0.1.0
  intl: ^0.16.0
  image_picker: ^0.6.7+7
  rxdart: ^0.24.1
  fluwx: ^2.6.2
  path_provider: ^1.6.18
  flutter_cache_manager: ^2.0.0
  open_file: ^3.0.1
  url_launcher: ^5.0.2
  flutter_speed_dial: ^1.0.9
  flutter_map: ^0.1.4
  month_picker_dialog: ^0.3.0
  autocomplete_textfield: ^1.6.4
  cached_network_image: 2.3.3
  flutter_spinkit: ^3.1.0
  store_redirect: ^1.0.1
  amap_location: ^0.2.0
  flutter_qq: ^0.0.4
  image_cropper: ^1.2.1
  jpush_flutter: ^0.6.3
  permission_handler: ^5.0.0+hotfix.1
  toast: ^0.1.5
  flutter_webview_plugin: ^0.3.11
  flutter_markdown: ^0.2.0
  convert: 2.1.1
  flutter_full_pdf_viewer: ^1.0.6
  provider: ^4.3.2+2
  date_range_picker: ^1.0.5
  common_utils: ^1.1.3
  flustars: ^0.2.6+1
  location_permissions: ^2.0.3
  city_pickers: ^0.1.29
  bot_toast: ^3.0.4
  gzx_dropdown_menu: ^1.0.3
  flutter_date_pickers: ^0.0.6
  flutter_alipay: ^0.1.2
  auto_orientation: ^1.0.6
  video_thumbnail: ^0.2.2
  device_info: ^0.4.2+8
  flutter_image_compress: ^0.7.0
  # qr_flutter: ^3.2.0
  flutter_staggered_grid_view: ^0.3.4
  pinput: ^1.0.0
  umeng_common_sdk: ^1.1.2
  qr_code_scanner: ^0.3.5
  flutter_qr_reader: ^1.0.3
  qr_flutter: ^3.2.0
  wechat_assets_picker: 4.2.2
  like_button: ^1.0.4
  sign_in_with_apple: ^2.5.4
  flutter_group_sliver: ^0.0.2
  # color_thief_flutter: ^1.0.2

  # PUB库钉钉插件
  flutter_ddshare: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.1
  json_serializable: 3.4.1

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - packages/assets/temp/lake.jpg
    - packages/assets/temp/login_logo.png
    - packages/assets/temp/logo1.png
    - packages/assets/temp/logo2.png
    - packages/assets/temp/picture.png
    - packages/assets/temp/pdf.png
    - packages/assets/temp/word.png
    - packages/assets/temp/excel.png
    - packages/assets/temp/business/check_report.png
    - packages/assets/temp/business/address_manage.png
    - packages/assets/temp/business/cart.png
    - packages/assets/temp/business/certicate_info.png
    - packages/assets/temp/business/clothes_manage.png
    - packages/assets/temp/business/customer_audit.png
    - packages/assets/temp/business/customer_service.png
    - packages/assets/temp/business/employee_manage.png
    - packages/assets/temp/business/inventory_manage.png
    - packages/assets/temp/business/invoice_manage.png
    - packages/assets/temp/business/member_manage.png
    - packages/assets/temp/business/my_account.png
    - packages/assets/temp/business/my_collection.png
    - packages/assets/temp/business/order_matter.png
    - packages/assets/temp/business/price_manage.png
    - packages/assets/temp/business/product_manage.png
    - packages/assets/temp/business/purchase_order.png
    - packages/assets/temp/business/requirement_order.png
    - packages/assets/temp/business/sale_order.png
    - packages/assets/temp/business/setting.png
    - packages/assets/temp/business/supplier_manage.png
    - packages/assets/temp/business/register_brand.png
    - packages/assets/temp/business/register_customer.png
    - packages/assets/temp/business/register_factory.png
    - packages/assets/temp/business/external_order.png
    - packages/assets/temp/business/outbound_order.png
    - packages/assets/temp/common/fast_factory.png
    - packages/assets/temp/common/find_factory.png
    - packages/assets/temp/common/idle_capacity.png
    - packages/assets/temp/common/order.png
    - data/province.json
    - data/province_only.json
    - data/province_only_whole_country.json
    - packages/assets/temp/login_background.png
    - packages/assets/temp/production/fab_add.png
    - packages/assets/temp/production/fab_create.png
    - packages/assets/temp/production/fab_only.png
    - packages/assets/temp/business/proofing.png
    - packages/assets/temp/my/address_manage.png
    - packages/assets/temp/my/certicate_info.png
    - packages/assets/temp/my/customer_service.png
    - packages/assets/temp/my/invoice_manage.png
    - packages/assets/temp/my/my_account.png
    - packages/assets/temp/my/setting.png
    - packages/assets/temp/my/help.png
    - packages/assets/temp/my/my_integral.png
    - packages/assets/temp/common/address_under_line.png
    - packages/assets/temp/business/partner_manage_factory.png
    - packages/assets/temp/business/product_manage_factory.png
    - packages/assets/temp/business/production_order_factory.png
    - packages/assets/temp/business/quote_manage_factory.png
    - packages/assets/temp/my/company_introduce.png
    - packages/assets/document/paymentProtocol.txt
    - packages/assets/document/serviceProtocol.txt
    - packages/assets/document/selectIdentity.txt
    - packages/assets/document/privacyProtocol.txt
    - packages/assets/temp/client_select.png
    - packages/assets/temp/QRCode.png
    - packages/assets/temp/common/icon64_wx_logo.png
    - packages/assets/temp/common/wechat_login.png
    - packages/assets/temp/common/apple.png
    - packages/assets/temp/common/mini-program.png
    - packages/assets/temp/common/wechat_friend.png
    - packages/assets/temp/common/qq_logo.png
    - packages/assets/temp/common/qq_zone.png
    - packages/assets/temp/common/qr_code.png
    - packages/assets/temp/system_msg.png
    - packages/assets/temp/money_msg.png
    - packages/assets/temp/select_contract.png
    - packages/assets/temp/select_order.png
    - packages/assets/temp/select_seal.png
    - packages/assets/temp/cgdd.png
    - packages/assets/temp/contract_help.png
    - packages/assets/temp/kjxy.png
    - packages/assets/temp/wtsc.png
    - packages/assets/temp/all_seal.png
    - packages/assets/temp/all_contract.png
    - packages/assets/temp/all_template.png
    - packages/assets/temp/icon/signed.png
    - packages/assets/temp/icon/not_signed.png
    - packages/assets/temp/icon/arrears.png
    - packages/assets/temp/icon/paid.png
    - packages/assets/temp/contract/all_contract.png
    - packages/assets/temp/contract/my_contract.png
    - packages/assets/temp/contract/my_seal.png
    - packages/assets/temp/contract/my_sign.png
    - packages/assets/temp/contract/other_sign.png
    - packages/assets/temp/index/contract_manage.png
    - packages/assets/temp/index/free_capacity.png
    - packages/assets/temp/index/nearby_factory.png
    - packages/assets/temp/index/order_coordination.png
    - packages/assets/temp/index/product_ordering.png
    - packages/assets/temp/index/production_factory.png
    - packages/assets/temp/index/quality_factory.png
    - packages/assets/temp/index/requirement.png
    - packages/assets/temp/index/unique_import.png
    - packages/assets/temp/index/material.png
    - packages/assets/temp/index/requirement_center.png
    - packages/assets/temp/index/free_capacity2.png
    - packages/assets/temp/index/materiel_products.png
    - packages/assets/img-temp/200x200/category.png
    - packages/assets/img-temp/200x200/tail_goods.png
    - packages/assets/img-temp/200x200/spot_goods.png
    - packages/assets/img-temp/200x200/future_goods.png
    - packages/assets/temp/20200411161233.png
    - packages/assets/temp/20200411161325.png
    - packages/assets/temp/20200414163706.png
    - packages/assets/temp/auth_fail.png
    - packages/assets/temp/auth_success.png
    - packages/assets/temp/common/dingding_logo.png
    - packages/assets/temp/business/delivery.png
    - packages/assets/temp/business/reconciliation.png
    - packages/assets/temp/business/price_order.png
    - packages/assets/temp/business/production_blue.png
    - packages/assets/temp/business/production_orange.png
    - packages/assets/temp/index/select_brand.png
    - packages/assets/temp/index/select_factory.png
    - packages/assets/temp/index/requirement_pool.png
    - packages/assets/temp/index/quote_process.png
    - packages/assets/temp/my/lucky_money.png
    - packages/assets/temp/activity/lucky_money2.png
    - packages/assets/temp/activity/gifit.png
    - packages/assets/temp/success.png
    - packages/assets/temp/icon/auth.png
    - packages/assets/temp/index/index_factory.jpg
    - packages/assets/temp/index/index_products.jpg
    - packages/assets/temp/index/index_requirement.jpg
    - packages/assets/temp/index/arrow.png
    - packages/assets/temp/index/home_communite.png
    - packages/assets/temp/index/home_contract.png
    - packages/assets/temp/index/home_factory.png
    - packages/assets/temp/index/home_production.png
    - packages/assets/temp/index/home_protect.png
    - packages/assets/temp/index/home_publish.png
    - packages/assets/temp/index/home_validate.png
    - packages/assets/temp/index/home_order.png
    - packages/assets/temp/index/home_deliver.png
    - packages/assets/temp/index/home_production_requirement.jpg
    - packages/assets/temp/index/home_publish_infos.jpg
    - packages/assets/temp/index/find_factory.png
    - packages/assets/temp/index/find_order.png
    - packages/assets/temp/empty-image-search.png
    - packages/assets/img/icons/b2b-v2/navigator/tab_1.0@2x.png
    - packages/assets/img/icons/b2b-v2/navigator/tab_1.1@2x.png
    - packages/assets/img/icons/b2b-v2/navigator/tab_2.0@2x.png
    - packages/assets/img/icons/b2b-v2/navigator/tab_2.1@2x.png
    - packages/assets/img/icons/b2b-v2/navigator/tab_3.0@2x.png
    - packages/assets/img/icons/b2b-v2/navigator/tab_3.1@2x.png
    - packages/assets/img/icons/b2b-v2/navigator/tab_4.0@2x.png
    - packages/assets/img/icons/b2b-v2/navigator/tab_4.1@2x.png
    - packages/assets/img/icons/b2b-v2/navigator/fab@2x.png
    - packages/assets/img/icons/b2b-v2/header/top_1@2x.png
    - packages/assets/img/icons/b2b-v2/header/top_2@2x.png
    - packages/assets/img/icons/b2b-v2/header/top_3@2x.png
    - packages/assets/img/icons/b2b-v2/main/tab_1@2x.png
    - packages/assets/img/icons/b2b-v2/main/tab_2@2x.png
    - packages/assets/img/icons/b2b-v2/main/tab_3@2x.png
    - packages/assets/img/icons/b2b-v2/main/tab_4@2x.png
    - packages/assets/img/icons/b2b-v2/main/tab_5@2x.png
    - packages/assets/img/icons/b2b-v2/main/tab_6@2x.png
    - packages/assets/img/icons/b2b-v2/main/tab_7@2x.png
    - packages/assets/img/icons/b2b-v2/main/tab_8@2x.png
    - packages/assets/img/icons/b2b-v2/notice@2x.png
    - packages/assets/img/icons/b2b-v2/auth_company@2x.png
    - packages/assets/img/icons/b2b-v2/auth_person@2x.png
    - packages/assets/img/icons/b2b-v2/search/del_1@2x.png
    - packages/assets/img/icons/b2b-v2/search/del_2@2x.png
    - packages/assets/img/icons/b2b-v2/location/add_1@2x.png
    - packages/assets/img/icons/b2b-v2/location/add_2@2x.png


  fonts:
    - family: b2bIcons
      fonts:
        - asset: lib/fonts/iconfont1.ttf
    - family: b2bIcons2
      fonts:
        - asset: lib/fonts/iconfont2.ttf
    - family: b2bIcons21
      fonts:
        - asset: lib/fonts/iconfont21.ttf
    - family: b2bIcons22
      fonts:
        - asset: lib/fonts/iconfont22.ttf
    - family: b2bIcons23
      fonts:
        - asset: lib/fonts/iconfont23.ttf
  # fonts:
  #   - family: b2bIcons
  #     fonts:
  #     - asset: packages/widgets/fonts/iconfont.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
