name: b2b_commerce
description: Hybris B2B Commerce.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  models:
    path: ../models/
  widgets:
    path: ../widgets/
  assets:
    path: ../assets/
  services:
    path: ../services/

  json_annotation: ^2.0.0
  cupertino_icons: ^0.1.2
  font_awesome_flutter: 8.2.0
  cached_network_image: ^0.4.1+1
  dio: 1.0.9
  shared_preferences: ^0.4.2
  transparent_image: ^0.1.0
  flutter_staggered_grid_view: "^0.2.4"
  intl: 0.15.7
  image_picker: ^0.4.10
  rxdart: ^0.20.0
  fluwx: ^0.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - packages/assets/temp/lake.jpg
    - packages/assets/temp/login_logo.png
    - packages/assets/temp/business/check_report.png
    - packages/assets/temp/business/address_manage.png
    - packages/assets/temp/business/cart.png
    - packages/assets/temp/business/certicate_info.png
    - packages/assets/temp/business/clothes_manage.png
    - packages/assets/temp/business/customer_audit.png
    - packages/assets/temp/business/customer_service.png
    - packages/assets/temp/business/employee_manage.png
    - packages/assets/temp/business/inventory_manage.png
    - packages/assets/temp/business/invoice_manage.png
    - packages/assets/temp/business/member_manage.png
    - packages/assets/temp/business/my_account.png
    - packages/assets/temp/business/my_collection.png
    - packages/assets/temp/business/order_matter.png
    - packages/assets/temp/business/price_manage.png
    - packages/assets/temp/business/product_manage.png
    - packages/assets/temp/business/purchase_order.png
    - packages/assets/temp/business/requirement_order.png
    - packages/assets/temp/business/sale_order.png
    - packages/assets/temp/business/setting.png
    - packages/assets/temp/business/supplier_manage.png
    - packages/assets/temp/business/register_brand.png
    - packages/assets/temp/business/register_customer.png
    - packages/assets/temp/business/register_factory.png

  fonts:
    - family: b2bIcons
      fonts:
        - asset: lib/fonts/iconfont1.ttf
  # fonts:
  #   - family: b2bIcons
  #     fonts:
  #     - asset: packages/widgets/fonts/iconfont.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
