name: b2b_commerce
description: Hybris B2B Commerce.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# Read more about versioning at semver.org.
version: 1.0.9+1

flutter_localizations:
  sdk: flutter

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  models:
    path: ../models/
  widgets:
    path: ../widgets/
  assets:
    path: ../assets/
  services:
    path: ../services/

  json_annotation: ^2.0.0
  cupertino_icons: ^0.1.2
  font_awesome_flutter: 8.2.0
  dio: ^2.0.18
  shared_preferences: ^0.4.2
  transparent_image: ^0.1.0
  flutter_staggered_grid_view: "^0.2.4"
  intl: ^0.15.7
  image_picker: ^0.6.0+10
  rxdart: ^0.20.0
  fluwx: ^0.6.2
  # photo_view: ^0.4.0
  photo_view: ^0.1.3
  path_provider: ^0.5.0+1
  flutter_cache_manager: ^0.3.0
  open_file: ^2.0.3
  url_launcher: ^5.0.2
  flutter_speed_dial: ^1.0.9
  flutter_map: ^0.1.4
  month_picker_dialog: ^0.0.8
  #  flutter_location_picker: 0.0.6
  city_pickers: ^0.1.12
  autocomplete_textfield: ^1.6.4
  pulltorefresh_flutter: "^0.1.9"
  cached_network_image: ^0.7.0
  flutter_spinkit: ^3.1.0
  store_redirect: ^1.0.1
  # image_gallery_saver: ^1.1.0
  alipay_me: ^1.0.0
  amap_location: ^0.2.0
  flutter_qq: ^0.0.4
  flutter_local_notifications: ^0.7.1+3
  image_picker_saver: ^0.3.0
  image_cropper: ^1.0.2
  jpush_flutter: ^0.0.11
  permission_handler: ^3.1.0
  flutter_widget_from_html: 0.2.0
  flutter_inappbrowser: 1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - packages/assets/temp/lake.jpg
    - packages/assets/temp/login_logo.png
    - packages/assets/temp/logo1.png
    - packages/assets/temp/logo2.png
    - packages/assets/temp/picture.png
    - packages/assets/temp/pdf.png
    - packages/assets/temp/word.png
    - packages/assets/temp/excel.png
    - packages/assets/temp/business/check_report.png
    - packages/assets/temp/business/address_manage.png
    - packages/assets/temp/business/cart.png
    - packages/assets/temp/business/certicate_info.png
    - packages/assets/temp/business/clothes_manage.png
    - packages/assets/temp/business/customer_audit.png
    - packages/assets/temp/business/customer_service.png
    - packages/assets/temp/business/employee_manage.png
    - packages/assets/temp/business/inventory_manage.png
    - packages/assets/temp/business/invoice_manage.png
    - packages/assets/temp/business/member_manage.png
    - packages/assets/temp/business/my_account.png
    - packages/assets/temp/business/my_collection.png
    - packages/assets/temp/business/order_matter.png
    - packages/assets/temp/business/price_manage.png
    - packages/assets/temp/business/product_manage.png
    - packages/assets/temp/business/purchase_order.png
    - packages/assets/temp/business/requirement_order.png
    - packages/assets/temp/business/sale_order.png
    - packages/assets/temp/business/setting.png
    - packages/assets/temp/business/supplier_manage.png
    - packages/assets/temp/business/register_brand.png
    - packages/assets/temp/business/register_customer.png
    - packages/assets/temp/business/register_factory.png
    - packages/assets/temp/common/fast_factory.png
    - packages/assets/temp/common/find_factory.png
    - packages/assets/temp/common/idle_capacity.png
    - packages/assets/temp/common/order.png
    - data/province.json
    - packages/assets/temp/login_background.png
    - packages/assets/temp/production/fab_add.png
    - packages/assets/temp/production/fab_create.png
    - packages/assets/temp/production/fab_only.png
    - packages/assets/temp/business/proofing.png
    - packages/assets/temp/my/address_manage.png
    - packages/assets/temp/my/certicate_info.png
    - packages/assets/temp/my/customer_service.png
    - packages/assets/temp/my/invoice_manage.png
    - packages/assets/temp/my/my_account.png
    - packages/assets/temp/my/setting.png
    - packages/assets/temp/my/help.png
    - packages/assets/temp/common/address_under_line.png
    - packages/assets/temp/business/partner_manage_factory.png
    - packages/assets/temp/business/product_manage_factory.png
    - packages/assets/temp/business/production_order_factory.png
    - packages/assets/temp/business/quote_manage_factory.png
    - packages/assets/temp/my/company_introduce.png
    - packages/assets/document/paymentProtocol.txt
    - packages/assets/document/serviceProtocol.txt
    - packages/assets/document/selectIdentity.txt
    - packages/assets/temp/client_select.png
    - packages/assets/temp/QRCode.png
    - packages/assets/temp/common/icon64_wx_logo.png
    - packages/assets/temp/common/wechat_friend.png
    - packages/assets/temp/common/qq_logo.png
    - packages/assets/temp/common/qq_zone.png
    - packages/assets/temp/system_msg.png
    - packages/assets/temp/money_msg.png

  fonts:
    - family: b2bIcons
      fonts:
        - asset: lib/fonts/iconfont1.ttf
    - family: b2bIcons2
      fonts:
        - asset: lib/fonts/iconfont2.ttf
  # fonts:
  #   - family: b2bIcons
  #     fonts:
  #     - asset: packages/widgets/fonts/iconfont.ttf
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
